#!/usr/bin/env python
# coding: utf-8

# # Primary vs Metastatic Metabolic Signaling Analysis
# 
# This notebook performs differential expression of metabolic target genes between primary and metastatic sites for a given cancer type, generating a volcano plot and an interactive table.
# It also integrates LIANA+ Cell-Cell Communication results to see which target genes are actively mediating signaling.
# 
# **Prerequisite:** Run `cancer_cellxgene_integration.ipynb` to generate the `.h5ad` and `_cellxgene_liana_results.csv` outputs first.

# In[38]:


import scanpy as sc
import pandas as pd
import numpy as np
import os
import glob
import matplotlib.pyplot as plt
import seaborn as sns
from plotly import express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import warnings
warnings.filterwarnings('ignore')

sc.settings.verbosity = 2
CANCER_TYPE_NAME = 'breast_cancer'


# ## 1. Configuration
# 
# Select the primary and metastatic base prefixes generated by `cancer_cellxgene_integration.ipynb`. We will load both `.h5ad` and LIANA+ `.csv` files using these prefixes to avoid overwriting.

# In[39]:


# Base directories
BASE_DIR = '../'
DATA_DIR = os.path.join(BASE_DIR, 'input', 'databases')
GLOBAL_OUTPUT_DIR = os.path.join(BASE_DIR, 'output')
OUTPUT_DIR = globals().get('OUTPUT_DIR', os.path.join(GLOBAL_OUTPUT_DIR, 'breast_cancer'))

# --- CONFIGURATION ---
# These will be dynamically overwritten during headless execution
h5ad_path = globals().get('h5ad_path', os.path.join(OUTPUT_DIR, 'breast_mammary-gland_liver_axilla_chest-wall_100k_whole_transcriptome_2025-11-08.h5ad'))
PRIMARY_TISSUES = ['breast']
# ---------------------

# Load the MetabConnectomeDB unique pairs to get target genes
metab_db_path = os.path.join(GLOBAL_OUTPUT_DIR, 'human_database_merge_unique_metab_target_pairs_with_HMDB_Info.csv')


# ## 2. Load Metabolic Target Vocabulary

# In[40]:


# Load the MetabConnectomeDB target genes
df_metab = pd.read_csv(metab_db_path)
df_metab['Target'] = df_metab['Target'].astype(str).str.split(r'[,;]')
df_metab = df_metab.explode('Target')
df_metab['Target'] = df_metab['Target'].str.strip()
df_metab = df_metab[df_metab['Target'] != 'nan'].dropna(subset=['Target'])
target_genes = set(df_metab['Target'].unique())
print(f"Loaded {len(target_genes):,} unique metabolic target genes from MetabConnectomeDB.")


# ## 3. Load LIANA+ Cell-Cell Communication Data

# In[41]:


liana_targets = set()

# Note: In the single-file pipeline, the LIANA results would ideally run on the combined .h5ad 
# as a separate script. If LIANA results are not present for the single file, we skip.
liana_file = h5ad_path.replace('.h5ad', '_cellxgene_liana_results.csv')

if os.path.exists(liana_file):
    df_liana = pd.read_csv(liana_file)
    liana_targets = set(df_liana['receptor_complex'].dropna().unique()).union(set(df_liana['ligand_complex'].dropna().unique()))
    print(f"Loaded LIANA results: {len(liana_targets)} genes involved in signaling.")
else:
    print(f"⚠️ LIANA file not found: {liana_file}")


# ## 4. Load and Merge scRNA-seq Data

# In[42]:


print(f"Loading Combined Data: {os.path.basename(h5ad_path)}")
adata = sc.read_h5ad(h5ad_path)

# Dynamically split Primary vs Metastasis based on the TISSUE column
adata.obs['site'] = np.where(adata.obs['tissue_general'].isin(PRIMARY_TISSUES), 'Primary', 'Metastasis')

print(f"Dataset shape: {adata.shape}")
print(adata.obs['site'].value_counts())


# ## 5. Perform Differential Expression (Metastasis vs Primary)

# In[47]:


# We use Wilcoxon rank-sum test to compare Metastasis vs Primary
print("Running Differential Expression...")
if len(adata.obs['site'].unique()) < 2:
    print(f"Warning: Cannot perform Main DE. Dataset only contains {list(adata.obs['site'].unique())} cells for these PRIMARY_TISSUES.")
    import numpy as np
    adata.uns['rank_genes_groups'] = {
        'names': np.rec.fromarrays([np.array([], dtype=object)], names=['Metastasis']),
        'scores': np.rec.fromarrays([np.array([], dtype=float)], names=['Metastasis']),
        'logfoldchanges': np.rec.fromarrays([np.array([], dtype=float)], names=['Metastasis']),
        'pvals': np.rec.fromarrays([np.array([], dtype=float)], names=['Metastasis']),
        'pvals_adj': np.rec.fromarrays([np.array([], dtype=float)], names=['Metastasis'])
    }
else:
    try:
        sc.tl.rank_genes_groups(adata, groupby='site', groups=['Metastasis'], reference='Primary', method='wilcoxon')
    except Exception as e:
        print(f"Warning: Cannot perform Main DE. Error: {e}")
        import numpy as np
        adata.uns['rank_genes_groups'] = {
            'names': np.rec.fromarrays([np.array([], dtype=object)], names=['Metastasis']),
            'scores': np.rec.fromarrays([np.array([], dtype=float)], names=['Metastasis']),
            'logfoldchanges': np.rec.fromarrays([np.array([], dtype=float)], names=['Metastasis']),
            'pvals': np.rec.fromarrays([np.array([], dtype=float)], names=['Metastasis']),
            'pvals_adj': np.rec.fromarrays([np.array([], dtype=float)], names=['Metastasis'])
        }

# Extract DE results
result = adata.uns['rank_genes_groups']

de_df = pd.DataFrame({
    'names': result['names']['Metastasis'],
    'scores': result['scores']['Metastasis'],
    'logfoldchanges': result['logfoldchanges']['Metastasis'],
    'pvals': result['pvals']['Metastasis'],
    'pvals_adj': result['pvals_adj']['Metastasis']
})

# Calculate -log10 p-value for Volcano plot
min_pval = de_df[de_df['pvals_adj'] > 0]['pvals_adj'].min()
de_df['pvals_adj_safe'] = de_df['pvals_adj'].replace(0, min_pval)
de_df['-log10(p_adj)'] = -np.log10(de_df['pvals_adj_safe'])

# Filter for Metabolic Target Genes
metab_de_df = de_df[de_df['names'].isin(target_genes)].copy()

# Add categories for plotting
metab_de_df['Significance'] = 'Not Significant'
metab_de_df.loc[(metab_de_df['pvals_adj'] < 0.05) & (metab_de_df['logfoldchanges'] > 0.5), 'Significance'] = 'Up in Metastasis'
metab_de_df.loc[(metab_de_df['pvals_adj'] < 0.05) & (metab_de_df['logfoldchanges'] < -0.5), 'Significance'] = 'Up in Primary'

print(f"Total Metabolic Target Genes analyzed: {len(metab_de_df)}")
print(metab_de_df['Significance'].value_counts())


# ## 6. Volcano Plot

# In[48]:


# Interactive Volcano Plot using Plotly
fig = px.scatter(
    metab_de_df,
    x='logfoldchanges',
    y='-log10(p_adj)',
    color='Significance',
    hover_name='names',
    hover_data=['pvals_adj', 'logfoldchanges'],
    color_discrete_map={
        'Not Significant': 'grey',
        'Up in Metastasis': 'red',
        'Up in Primary': 'blue'
    },
    title=f"Volcano Plot: Metastatic vs Primary (Metabolic Target Genes - {CANCER_TYPE_NAME})",
    labels={'logfoldchanges': 'Log2 Fold Change (Metastasis vs Primary)', '-log10(p_adj)': '-Log10(Adjusted P-Value)'}
)

# Add cutoff lines
fig.add_vline(x=0.5, line_dash="dash", line_color="black")
fig.add_vline(x=-0.5, line_dash="dash", line_color="black")
fig.add_hline(y=-np.log10(0.05), line_dash="dash", line_color="black")

fig.update_layout(width=900, height=700)
# Display interactive Plotly using IPython display so it renders in HTML exports
try:
    from IPython.display import display, HTML
    display(HTML(fig.to_html(full_html=False, include_plotlyjs="cdn")))
except Exception as e:
    print(f"Could not render Plotly inline: {e}")
    fig.show()

# Optional: Static Seaborn plot


# ## 7. Results Table Export with LIANA+ Annotations

# In[49]:


# Annotate whether the gene appears in the LIANA communication networks
def get_liana_status(gene):
    if gene in liana_targets: return 'Yes'
    return 'No'
metab_de_df['LIANA_Active_Network'] = metab_de_df['names'].apply(get_liana_status)

# Merge with our metabolite database
df_metab_summary = df_metab.groupby('Target').agg({
    'Metabolite_Name': lambda x: '; '.join(set(x.dropna().astype(str))),
    'HMDB_ID': lambda x: '; '.join(set(x.dropna().astype(str)))
}).reset_index()

results_table = metab_de_df.merge(df_metab_summary, left_on='names', right_on='Target', how='left')
results_table = results_table.drop(columns=['Target', 'pvals_adj_safe'])
results_table = results_table.sort_values('pvals_adj')

# Display the top significant targets
from IPython.display import display, HTML
display(HTML(results_table.head(30).to_html()))

# Save to a dynamically named CSV to prevent overwriting
output_csv = os.path.join(OUTPUT_DIR, f'primary_vs_metastasis_{CANCER_TYPE_NAME}_DE_metabolic_targets.csv')
results_table.to_csv(output_csv, index=False)
print(f"Results table saved to: {output_csv}")


# ## 8. Site-Specific Metastatic Convergence (Niche Comparison)
# 
# If the metastatic dataset contains cells from multiple distinct sites (e.g., Liver vs Brain vs Bone), we will automatically separate them and run DE for each site independently against the primary tumor. An UpSetPlot will be generated to visualize which metabolic target genes are universally upregulated across all metastatic sites (conserved signature) versus those that are unique to a specific niche.

# In[50]:


# Check if we have multiple metastatic sites
meta_sites = [t for t in adata[adata.obs['site'] == 'Metastasis'].obs['tissue_general'].unique() if pd.notnull(t)]

if len(meta_sites) > 1:
    print(f"Found multiple metastatic niches: {meta_sites}\nRunning site-specific DE...")

    # We need UpSetPlot for visualization
    try:
        from upsetplot import from_contents, plot
    except ImportError:
        import subprocess
        print("Installing upsetplot...")
        subprocess.check_call(['pip', 'install', 'upsetplot'])
        from upsetplot import from_contents, plot

    site_significant_genes = {}

    for site in meta_sites:
        # Create a subset with just the primary cells and THIS specific metastatic site
        adata_site = adata[(adata.obs['tissue_general'] == site) | (adata.obs['site'] == 'Primary')].copy()
        adata_site.obs['comparison_group'] = adata_site.obs.apply(lambda x: site if x['site'] == 'Metastasis' else 'Primary', axis=1)

        try:
            if len(adata_site.obs['comparison_group'].unique()) < 2:
                print(f"Warning: Not enough groups for site {site}")
                continue
            sc.tl.rank_genes_groups(adata_site, groupby='comparison_group', groups=[site], reference='Primary', method='wilcoxon')
            result = adata_site.uns['rank_genes_groups']

            # Filter for significant metabolic targets
            site_df = pd.DataFrame({
                'names': result['names'][site],
                'logfoldchanges': result['logfoldchanges'][site],
                'pvals_adj': result['pvals_adj'][site]
            })

            # Significant up-regulated in metastasis
            sig_up = site_df[(site_df['names'].isin(target_genes)) & 
                             (site_df['pvals_adj'] < 0.05) & 
                             (site_df['logfoldchanges'] > 0.5)]['names'].tolist()

            if len(sig_up) > 0:
                site_significant_genes[site] = sig_up
                print(f" - {site}: {len(sig_up)} upregulated metabolic targets")
            else:
                print(f" - {site}: 0 upregulated metabolic targets found. Skipping for plot.")

        except Exception as e:
            print(f" - {site}: Could not run DE (maybe not enough cells). Error: {e}")

    if len(site_significant_genes) > 0:
        import matplotlib.pyplot as plt
        fig = plt.figure(figsize=(10, 6))
        upset_data = from_contents(site_significant_genes)
        axes = plot(upset_data, show_counts=True, sort_by='cardinality', fig=fig)
        plt.suptitle(f"Metastatic Convergence: Upregulated Targets across Niches", fontsize=14, y=1.05)
        plt.show()

        # Output the intersection (the pan-metastatic signature)
        if len(site_significant_genes) >= 2:
            common_genes = set.intersection(*[set(g) for g in site_significant_genes.values()])
            print(f"\n🔥 Pan-Metastatic Conserved Targets ({len(common_genes)} genes):")
            print(list(common_genes))
else:
    print(f"Only one or zero metastatic sites found ({meta_sites}). Site-specific comparison skipped.")


# ## Automated HTML Export
# 
# Generate a styled HTML report of this notebook for sharing and viewing.

# In[51]:


import subprocess
import sys
import os

notebook_filename = 'primary_vs_metastasis_comparison.ipynb'

# remove extension for nbconvert
output_base = output_csv.replace(".csv", "")

print(f"Executing full notebook HTML export for '{notebook_filename}'...")

# Get Jupyter binary
jupyter_bin = os.path.join(os.path.dirname(sys.executable), 'jupyter')
if not os.path.exists(jupyter_bin):
    jupyter_bin = 'jupyter'

cmd_html = [
    jupyter_bin,
    "nbconvert",
    "--to", "html",
    notebook_filename,
    "--output", output_base
]

res_html = subprocess.run(cmd_html, capture_output=True, text=True)

if res_html.returncode == 0:
    print("🎉 SUCCESS: Notebook successfully exported as a styled HTML report!")
    print(f"   -> Saved to: '{output_base}.html'")
else:
    print("❌ HTML export failed.")
    print(res_html.stderr)


# In[ ]:




