import os

d = "output/pan_cancer_meta_results"
suffix_100 = "_5MetCan_100k"
suffix_500 = "_5MetCan_500k"

# Specific renames
renames = {
    "pan_cancer_23_genes.csv": f"pan_cancer_conserved_genes{suffix_100}.csv",
    "pan_cancer_23_genes_with_annotation.csv": f"pan_cancer_conserved_genes_with_annotation{suffix_100}.csv",
}

for old, new in renames.items():
    if os.path.exists(os.path.join(d, old)):
        os.rename(os.path.join(d, old), os.path.join(d, new))

# General renames for any .csv or .png without a suffix
for f in os.listdir(d):
    if f.endswith(".csv") or f.endswith(".png"):
        if "5MetCan" not in f:
            if f in ["pan_cancer_conserved_genes.csv", "upset_plot_data.csv", "upset_plot.png", "metabolite_target_network.png", "metabolite_target_network_edges.csv"]:
                # these were just generated by the 500k run prior to the suffix patch
                new_suffix = suffix_500
            else:
                # everything else (e.g. primary signature plots/CSVs) is from the 100k run
                new_suffix = suffix_100
                
            name, ext = os.path.splitext(f)
            new_name = f"{name}{new_suffix}{ext}"
            os.rename(os.path.join(d, f), os.path.join(d, new_name))
            print(f"Renamed {f} to {new_name}")
