import re

import sys
if '..' not in sys.path: sys.path.append('..')
from pan_cancer_config import ANALYSIS_SUFFIX

md_file = 'output/AI_summary_and_insights.md'
with open(md_file, 'r') as f:
    content = f.read()

# Fix 1: Conserved gene signature
prov1 = f"""> [!NOTE]
> **Data Provenance**
> - **Source File:** `output/ai_summary_tables/conserved_gene_directed_signature_annotation{ANALYSIS_SUFFIX}.csv`
> - **Scripts:** `scripts/generate_ai_summary_tables.py`, `scripts/fetch_uniprot_roles.py`, `scripts/fetch_opentargets.py`

"""
content = re.sub(
    r'\*Generated by scripts:.*?\*\n+',
    prov1,
    content,
    count=1
)

# Fix 2: Total Candidates table
prov2 = f"""> [!NOTE]
> **Data Provenance**
> - **Source File:** `output/pan_cancer_meta_results/dataset_overview{ANALYSIS_SUFFIX}.csv` and DE meta-analysis files
> - **Scripts:** `scripts/generate_ai_summary_tables.py` (for automated version)

"""
content = re.sub(
    r'(\| Cancer \| Total Candidates \| Unique Targets \| Unique Metabolites \| Top Target \(by LFC\) \|)',
    prov2 + r'\1',
    content,
    count=1
)

# Fix 3: Metabolic Target Genes
prov3 = f"""> [!NOTE]
> **Data Provenance**
> - **Source File:** `output/pan_cancer_meta_results/metastatic_enrichment_summary{ANALYSIS_SUFFIX}.csv`
> - **Scripts:** `scripts/generate_ai_summary_tables.py` (for automated version)

"""
content = re.sub(
    r'(\| Cancer \| Metabolic Target Genes \| Max Cell Types/Target \| Mean Cell Types/Target \| Most Broadly Expressed \|)',
    prov3 + r'\1',
    content,
    count=1
)

# Fix 4: Unique Metastatic Targets
prov4 = f"""> [!NOTE]
> **Data Provenance**
> - **Source File:** `output/pan_cancer_meta_results/cancer_specific_unique_signatures{ANALYSIS_SUFFIX}.csv`
> - **Scripts:** `scripts/generate_ai_summary_tables.py` (for automated version)

"""
content = re.sub(
    r'(\| Cancer \| Unique Metastatic Targets \| Key Unique Hits \| Metabolic Theme \|)',
    prov4 + r'\1',
    content,
    count=1
)

with open(md_file, 'w') as f:
    f.write(content)
print("Added provenance notes.")
