import nbformat as nbf
import sys
import os

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from scripts import serotonin_config as cfg

nb = nbf.v4.new_notebook()

# ---------------------------------------------------------
# Cell 1: Setup and Imports
# ---------------------------------------------------------
markdown_1 = """# Ovarian Cancer Serotonin-Immune Evasion Analysis

### Goal
To analyze if ovarian peritoneal metastases exploit serotonin signaling for immune evasion using empirical scRNA-seq and Visium spatial transcriptomics.

### Purpose
To definitively evaluate the hypothesis: **"Do ovarian peritoneal metastases exploit serotonin signaling for immune evasion?"** by integrating >800,000 single cells and 8 spatial tumor maps.

### Interpretation
- **Empirical scRNA-seq:** Higher evasion scores in the metastatic niches (abdomen, omentum, uterus) compared to the primary tumor (ovary) empirically confirm active immune suppression via the Serotonin/HTR7 axis.
- **Spatial Visium:** Physical colocalization of HTR7+ TAMs with T-cell Exhaustion markers spatially validates the presence of these local suppressive niches.

**Prerequisites:** 
This notebook relies on the outputs generated by two scripts:
1. `scripts/compute_metastatic_immune_evasion.py` (generates the scRNA-seq `.h5ad` and metadata CSVs)
2. `scripts/verify_spatial_immune_evasion.py` (formats the Visium RAW data into loadable `tmp_visium_loaders` directories)

*Note: This notebook was dynamically generated by `scripts/generate_immune_evasion_notebook.py`.*
"""
code_1 = """import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scanpy as sc
import os

# Set plotting styles
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['figure.dpi'] = 100
sns.set_theme(style="whitegrid")

DATA_DIR = "../output/serotonin_axis_spatial_mapping"
SPATIAL_DIR = "../output/serotonin_axis_spatial_mapping/tmp_visium_loaders"
H5AD_PATH = "../output/ovarian_full_uncapped_cellxgene.h5ad"
"""

# ---------------------------------------------------------
# Cell 2: Load and Visualize scRNA-seq Data
# ---------------------------------------------------------
markdown_2 = """## 1. Single-Cell RNA-seq Analysis (Primary vs Metastasis)

First, we load the metadata generated from scoring 810k cells for immune evasion signatures. We will visualize the enrichment of these scores in TAMs and T/NK cells across Primary and Metastatic niches."""
code_2 = """# Load scRNA-seq metadata
metadata_path = os.path.join(DATA_DIR, "immune_evasion_metadata.csv")
df_meta = pd.read_csv(metadata_path, index_col=0)

print(f"Total cells loaded: {len(df_meta):,}")
print(df_meta['cell_type'].value_counts().head(10))

# Filter to just Macrophages/Monocytes and T/NK cells for specific scoring
df_macs = df_meta[df_meta['Is_Macrophage'] == True].copy()
df_tnk = df_meta[df_meta['Is_T_NK_Cell'] == True].copy()

# Add a Niche column
def get_niche(row):
    if row['Is_Metastatic']: return 'Metastatic'
    if row['Is_Primary']: return 'Primary'
    return 'Other'

df_macs['Niche'] = df_macs.apply(get_niche, axis=1)
df_tnk['Niche'] = df_tnk.apply(get_niche, axis=1)

# Filter out 'Other'
df_macs = df_macs[df_macs['Niche'].isin(['Primary', 'Metastatic'])]
df_tnk = df_tnk[df_tnk['Niche'].isin(['Primary', 'Metastatic'])]

# Save plotting data to CSVs so the summary script can use them
macs_csv = os.path.join(DATA_DIR, 'plot_data_macs.csv')
tnk_csv = os.path.join(DATA_DIR, 'plot_data_tnk.csv')
df_macs.to_csv(macs_csv)
df_tnk.to_csv(tnk_csv)
print(f"Saved {len(df_macs)} macrophages to {macs_csv}")
print(f"Saved {len(df_tnk)} T/NK cells to {tnk_csv}")


# Optionally, you can load the raw .h5ad matrix here for deeper gene-level analysis
print(f"\\nLooking for raw scRNA-seq AnnData matrix at: {H5AD_PATH}")
if os.path.exists(H5AD_PATH):
    adata_scrna = sc.read_h5ad(H5AD_PATH, backed='r')
    print(f"Successfully connected to the raw .h5ad scRNA-seq dataset:")
    print(adata_scrna)
else:
    print(f"H5AD file not found at {H5AD_PATH}. Ensure `compute_metastatic_immune_evasion.py` has been run.")
"""

# ---------------------------------------------------------
# Cell 3: Violin Plots
# ---------------------------------------------------------
markdown_3 = """### Enrichment of HTR7+ TAMs and Exhaustion in Metastasis

### Purpose
To visualize the distribution of immune evasion scores across niches and calculate the statistical significance (p-value) of the metastatic enrichment.

### Interpretation
A highly significant p-value (p < 0.05) combined with a positive shift in the violin plot confirms that the metastatic niche is actively upregulating these immune evasion and serotonin signatures compared to the primary tumor."""
import math

# Load plotting config from serotonin_config
plot_config = cfg.serotonin_axis.get('PLOTTING_CONFIG', [])
num_plots = len(plot_config)
cols = 2
rows = math.ceil(num_plots / cols)

code_3 = f"""from scipy.stats import mannwhitneyu

fig, axes = plt.subplots({rows}, {cols}, figsize=(15, 6 * {rows}))
axes = axes.flatten()

def plot_with_pval(data, x, y, ax, title):
    import seaborn as sns
    sns.violinplot(data=data, x=x, y=y, palette=['#1f77b4', '#d62728'], ax=ax)
    
    # Calculate P-value
    group_primary = data[data[x] == 'Primary'][y].dropna()
    group_meta = data[data[x] == 'Metastatic'][y].dropna()
    
    if len(group_primary) > 0 and len(group_meta) > 0:
        stat, pval = mannwhitneyu(group_primary, group_meta, alternative='two-sided')
        pval_str = f"P = {{pval:.2e}}" if pval < 0.001 else f"P = {{pval:.4f}}"
        ax.set_title(f"{{title}}\\n({{pval_str}})")
    else:
        ax.set_title(title)
    ax.set_ylabel("Score")

"""

for i, p_cfg in enumerate(plot_config):
    score_col = p_cfg['score_col']
    title = p_cfg['title']
    target_df = p_cfg['cell_target']
    code_3 += f"# {i+1}. {title}\n"
    code_3 += f"plot_with_pval({target_df}, 'Niche', '{score_col}', axes[{i}], '{title}')\n\n"

# Turn off any unused subplots
for j in range(num_plots, rows * cols):
    code_3 += f"axes[{j}].axis('off')\n"

code_3 += "plt.tight_layout()\nplt.show()\n"


# ---------------------------------------------------------
# Cell 4: Visium Spatial Transcriptomics
# ---------------------------------------------------------
markdown_4 = """## 2. Spatial Transcriptomics (Visium)

### Purpose
To map the spatial localization of the Serotonin Synthesis/Receptor signature and its overlap with Immune Evasion in the physical tumor microenvironment. We loop over all 8 samples (SP1 to SP8) to interactively display the spatial overlays.

### Interpretation
Spatial overlap (spots showing high intensity for both HTR7+ TAMs and Exhaustion) physically validates the single-cell finding that serotonin signaling establishes local immune evasion niches."""
code_4 = """import glob
import json
from matplotlib.image import imread

def load_visium_sample(sample_id):
    \"\"\"Loads a Visium sample from MTX array and spatial coordinates.\"\"\"
    sample_dir = os.path.join(SPATIAL_DIR, f"tmp_10x_{sample_id}")
    if not os.path.exists(sample_dir):
        print(f"Directory not found for {sample_id} at {sample_dir}")
        return None
        
    try:
        adata = sc.read_10x_mtx(sample_dir)
        spatial_dir = os.path.join(sample_dir, "spatial")
        
        tissue_pos_file = os.path.join(spatial_dir, "tissue_positions.csv")
        has_header = True
        if not os.path.exists(tissue_pos_file):
            tissue_pos_file = os.path.join(spatial_dir, "tissue_positions_list.csv")
            has_header = False
            
        positions = pd.read_csv(tissue_pos_file, header=0 if has_header else None, index_col=0)
        positions.columns = ["in_tissue", "array_row", "array_col", "pxl_col_in_fullres", "pxl_row_in_fullres"]
        adata.obs = adata.obs.join(positions, how="left")
        adata.obsm["spatial"] = adata.obs[["pxl_row_in_fullres", "pxl_col_in_fullres"]].to_numpy()
        
        library_id = "sample"
        adata.uns["spatial"] = {library_id: {"images": {}, "scalefactors": {}, "metadata": {}}}
        
        for key, filename in [("hires", "tissue_hires_image.png"), ("lowres", "tissue_lowres_image.png")]:
            path = os.path.join(spatial_dir, filename)
            if os.path.exists(path):
                adata.uns["spatial"][library_id]["images"][key] = imread(path)
                
        scale_path = os.path.join(spatial_dir, "scalefactors_json.json")
        if os.path.exists(scale_path):
            with open(scale_path, 'r') as f:
                adata.uns["spatial"][library_id]["scalefactors"] = json.load(f)
                
        adata.var_names_make_unique()
        return adata
    except Exception as e:
        print(f"Failed to load {sample_id}: {e}")
        return None

samples = [f"SP{i}" for i in range(1, 9)]
"""

# ---------------------------------------------------------
# Cell 5: Scoring spatial
# ---------------------------------------------------------
code_5 = """import sys
sys.path.append('.')
import serotonin_config as cfg
import scipy.sparse

def score_spatial(adata):
    # Normalize
    sc.pp.normalize_total(adata, target_sum=1e4)
    sc.pp.log1p(adata)
    
    # 1. HTR7 TAM Signature
    valid_tam = [g for g in cfg.HTR7_TAM_SIGNATURE if g in adata.var_names]
    if valid_tam:
        adata.obs['HTR7_TAM_Score'] = adata[:, valid_tam].X.mean(axis=1).A1 if scipy.sparse.issparse(adata.X) else adata[:, valid_tam].X.mean(axis=1)
    
    # 2. Exhaustion Targets
    valid_exh = [g for g in cfg.EXHAUSTION_TARGETS if g in adata.var_names]
    if valid_exh:
        adata.obs['Exhaustion_Score'] = adata[:, valid_exh].X.mean(axis=1).A1 if scipy.sparse.issparse(adata.X) else adata[:, valid_exh].X.mean(axis=1)
        
    # 3. Suppressive Ligands
    valid_sup = [g for g in cfg.SUPPRESSIVE_LIGAND_TARGETS if g in adata.var_names]
    if valid_sup:
        adata.obs['Suppressive_Ligands_Score'] = adata[:, valid_sup].X.mean(axis=1).A1 if scipy.sparse.issparse(adata.X) else adata[:, valid_sup].X.mean(axis=1)
"""

# ---------------------------------------------------------
# Cell 6: Loop over samples
# ---------------------------------------------------------
code_6 = """# Interactive spatial plots for all 8 samples
for sample_id in samples:
    print(f"\\n{'='*50}\\nProcessing Sample {sample_id}\\n{'='*50}")
    adata = load_visium_sample(sample_id)
    if adata is None:
        continue
        
    score_spatial(adata)
    
    # Check which scores were successfully added
    scores_to_plot = []
    for s in ['HTR7_TAM_Score', 'Exhaustion_Score', 'Suppressive_Ligands_Score']:
        if s in adata.obs.columns:
            scores_to_plot.append(s)
            
    if scores_to_plot:
        sc.pl.spatial(
            adata, 
            color=scores_to_plot, 
            cmap="magma", 
            spot_size=1.5,
            title=[f"{sample_id}: {s}" for s in scores_to_plot],
            show=True
        )
    else:
        print(f"No target genes found for {sample_id}")
"""

# ---------------------------------------------------------
# Cell 7: Colocalization Summary
# ---------------------------------------------------------
markdown_7 = """### Colocalization Statistics

### Purpose
To aggregate the spot-level Pearson correlations between HTR7+ TAMs and Exhaustion markers across all 8 spatial samples.

### Interpretation
A consistent positive Pearson Correlation across the samples indicates that the presence of HTR7+ TAMs is robustly linked to a highly exhausted T-cell state in the spatial microenvironment."""
code_7 = """coloc_path = os.path.join(DATA_DIR, "visium_immune_evasion_summary.csv")
if os.path.exists(coloc_path):
    df_coloc = pd.read_csv(coloc_path)
    print("Spatial Colocalization Summary:")
    display(df_coloc)
    
    # Plot
    if not df_coloc.empty:
        plt.figure(figsize=(10, 6))
        sns.barplot(data=df_coloc, x='Sample', y='Pearson_R', palette='viridis')
        plt.title('Spatial Colocalization of HTR7+ TAMs and Exhaustion Markers')
        plt.ylabel("Pearson Correlation")
        plt.xticks(rotation=45)
        plt.show()
else:
    print(f"Summary file not found at {coloc_path}")
"""

# ---------------------------------------------------------
# Cell 8: Save to HTML
# ---------------------------------------------------------
markdown_8 = """## 3. Export to HTML

### Purpose
To automatically export this executed Jupyter Notebook to a static HTML file for easy sharing and documentation.
"""
code_8 = """import os
import subprocess
import sys

notebook_filename = 'ovarian_serotonin_immune_evasion.ipynb'
output_base = 'ovarian_serotonin_immune_evasion'
output_dir = os.path.join('..', 'output', 'serotonin_axis_spatial_mapping')
os.makedirs(output_dir, exist_ok=True)

jupyter_bin = os.path.join(os.path.dirname(sys.executable), 'jupyter')
if not os.path.exists(jupyter_bin): jupyter_bin = 'jupyter'

cmd_html = [jupyter_bin, "nbconvert", "--to", "html", notebook_filename, "--output-dir", output_dir, "--output", output_base]
res_html = subprocess.run(cmd_html, capture_output=True, text=True)

if res_html.returncode == 0:
    print(f"🎉 SUCCESS: Notebook exported to '{os.path.join(output_dir, output_base)}.html'")
else:
    print("❌ HTML export failed.")
    print(res_html.stderr)
"""

print_config_code = """
print('--- INJECTED PIPELINE CONFIGURATION ---')
from pan_cancer_config import STRICT_MASK_CANCERS, CANCER_PRIMARY_TISSUE
print(f'STRICT_MASK_CANCERS: {STRICT_MASK_CANCERS}')
print(f'CANCER_PRIMARY_TISSUE: {CANCER_PRIMARY_TISSUE}')
"""

nb['cells'] = [
    nbf.v4.new_code_cell(print_config_code),
    nbf.v4.new_markdown_cell(markdown_1),
    nbf.v4.new_code_cell(code_1),
    nbf.v4.new_markdown_cell(markdown_2),
    nbf.v4.new_code_cell(code_2),
    nbf.v4.new_markdown_cell(markdown_3),
    nbf.v4.new_code_cell(code_3),
    nbf.v4.new_markdown_cell(markdown_4),
    nbf.v4.new_code_cell(code_4),
    nbf.v4.new_code_cell(code_5),
    nbf.v4.new_code_cell(code_6),
    nbf.v4.new_markdown_cell(markdown_7),
    nbf.v4.new_code_cell(code_7),
    nbf.v4.new_markdown_cell(markdown_8),
    nbf.v4.new_code_cell(code_8),
]

with open('scripts/ovarian_serotonin_immune_evasion.ipynb', 'w') as f:
    nbf.write(nb, f)

print("Successfully generated scripts/ovarian_serotonin_immune_evasion.ipynb")
