import pandas as pd
import re
import os
import sys

if '..' not in sys.path: sys.path.append('..')
from pan_cancer_config import ANALYSIS_SUFFIX

md_file = 'output/AI_summary_and_insights.md'
with open(md_file, 'r') as f:
    content = f.read()

# Helper to generate table markdown from df
def df_to_markdown(df):
    md = f"*Generated by script: `scripts/generate_ai_summary_tables.py`*\n\n"
    # Column headers
    md += "| " + " | ".join(df.columns) + " |\n"
    # Separator
    md += "|" + "|".join([":---" for _ in df.columns]) + "|\n"
    # Rows
    for _, row in df.iterrows():
        md += "| " + " | ".join([str(val) for val in row.values]) + " |\n"
    return md

# 1. Dataset Overview
df_overview = pd.read_csv(f'output/ai_summary_tables/dataset_overview{ANALYSIS_SUFFIX}.csv')
table_overview = df_to_markdown(df_overview)
# Replace the table starting with | Cancer | Total Candidates |
content = re.sub(
    r'\| Cancer \| Total Candidates \|.*?(?=\n\n)',
    table_overview.strip(),
    content,
    flags=re.DOTALL
)

# 2. Metastatic Enrichment
df_enrich = pd.read_csv(f'output/ai_summary_tables/metastatic_enrichment_summary{ANALYSIS_SUFFIX}.csv')
table_enrich = df_to_markdown(df_enrich)
# Replace the table starting with | Cancer | Metabolic Target Genes |
content = re.sub(
    r'\| Cancer \| Metabolic Target Genes \|.*?(?=\n\n)',
    table_enrich.strip(),
    content,
    flags=re.DOTALL
)

# 3. Unique Signatures
df_unique = pd.read_csv(f'output/ai_summary_tables/cancer_specific_unique_signatures{ANALYSIS_SUFFIX}.csv')
table_unique = df_to_markdown(df_unique)
# Replace the table starting with | Cancer | Unique Metastatic Targets |
content = re.sub(
    r'\| Cancer \| Unique Metastatic Targets \|.*?(?=\n\n)',
    table_unique.strip(),
    content,
    flags=re.DOTALL
)

with open(md_file, 'w') as f:
    f.write(content)
print("Updated all tables in markdown.")
